### ISSUE TITLE
formatOnSave + prettier doesn't work on output.js files

### ISSUE THREAD

**Issue by ZihanChen-MSFT** [alloy/flow2dts#1]
Prettier doesn't recognize TypeScript while editing `*.js` files. For example, in TypeScript object literal type uses ";" to end properties, but prettier always change them to ",".

One possible solution could be fixing `pluginTester`+`fixtureOutputExit`, I guess it should behave differently for `*.d.ts` files.

**Comment by alloy** [comment]
Fixed by 294098c06561e63137fc615d3c0972c86398e41f
