### ISSUE TITLE
Problems getting types from prop-types package

### ISSUE THREAD

**Issue by alloy** [alloy/flow2dts#11]
The [`@types/prop-types` package](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/prop-types/index.d.ts) exports only _value_ versions of the checkers, not _type_ versions, which means a declaration like this:

```ts
import PropTypes from "prop-types"
declare var LayoutPropTypes: {
  borderWidth: PropTypes.number
}
```

…leads to an error like:

```
workbench/outputs/ios/Libraries/DeprecatedPropTypes/DeprecatedLayoutPropTypes.d.ts - error TS2694: Namespace '"node_modules/@types/prop-types/index"' has no exported member 'number'.
```

Exporting a type called `number` is always going to be tough, in fact [babel-plugin-syntax-flow doesn't parse it](https://flow.org/try/#0JYWwDg9gTgLgBABShMAVAnmApgZzgM2RDgCIxkwBaGTXEgKBuzgA04BeRCjbHAOgB2AVxAAjLFCA).

The most compatible solution might be to update the RN source to get the types from the values instead:

```ts
import PropTypes from "prop-types"
declare var LayoutPropTypes: {
  borderWidth: typeof PropTypes.number
}
```

**Comment by ZihanChen-MSFT** [comment]
```
workbench/outputs/ios/Libraries/Components/Picker/PickerIOS.d.ts:25:16 - error TS2694: Namespace 'React' has no exported member 'ChildrenArray'.
workbench/outputs/ios/Libraries/Utilities/ReactNativeTestTools.d.ts:8:53 - error TS2694: Namespace '"C:/Code/ZihanChen-MSFT/flow2dts/node_modules/@types/react-test-renderer/index"' has no exported member 'create'.
```

reduced to only 2, will take a further look

**Comment by ZihanChen-MSFT** [comment]
ChildrenArray and create could be hardcoded, close this first since it becomes are different issue.
