### ISSUE TITLE
Don't strip exported identifiers

### ISSUE THREAD

**Issue by alloy** [alloy/flow2dts#21]
See [this failing test](https://github.com/alloy/flow2dts/commit/942b63cc4e37f741a87fb1d4de157cbe85a81dd6) and [remove override](https://github.com/alloy/flow2dts/commit/21f327d1e4e685458a81e29e35979b9a27242618) once fixed.

**Comment by ZihanChen-MSFT** [comment]
Fixed by 7cfcc4e
