### ISSUE TITLE
Don't lose typeof on values

### ISSUE THREAD

**Issue by alloy** [alloy/flow2dts#22]
See [this failing test](https://github.com/alloy/flow2dts/commit/73aace2d9f01b8b8ebddc8d48a923a2b78a10697) and remove [this override](https://github.com/alloy/flow2dts/commit/fbdbfd41d1f0462c2d38ab807f33226bca59d749) when fixed.

**Comment by ZihanChen-MSFT** [comment]
Fixed by 7cfcc4e
